export const GET_BOOKMARKS_REQUEST = "GET_BOOKMARKS_REQUEST";
export const GET_BOOKMARKS_SUCCESS = "GET_BOOKMARKS_SUCCESS";
export const GET_BOOKMARKS_FAIL = "GET_BOOKMARKS_FAIL";
export const ADD_BOOKMARKS_REQUEST = "ADD_BOOKMARKS_REQUEST";
export const ADD_BOOKMARKS_SUCCESS = "ADD_BOOKMARKS_SUCCESS";
export const ADD_BOOKMARKS_FAIL = "ADD_BOOKMARKS_FAIL";
