export const GET_BOOKMARKS_REQUEST = "GET_BOOKMARKS_REQUEST";
export const GET_BOOKMARKS_SUCCESS = "GET_BOOKMARKS_SUCCESS";
export const GET_BOOKMARKS_FAIL = "GET_BOOKMARKS_FAIL";
export const ADD_BOOKMARKS_REQUEST = "ADD_BOOKMARKS_REQUEST";
export const ADD_BOOKMARKS_SUCCESS = "ADD_BOOKMARKS_SUCCESS";
export const ADD_BOOKMARKS_FAIL = "ADD_BOOKMARKS_FAIL";
export const REMOVE_BOOKMARK_REQUEST = "REMOVE_BOOKMARK_REQUEST";
export const REMOVE_BOOKMARK_SUCCESS = "REMOVE_BOOKMARK_SUCCESS";
export const REMOVE_BOOKMARK_FAIL = "REMOVE_BOOKMARK_FAIL";
export const REMOVE_ALL_BOOKMARKS_REQUEST = "REMOVE_ALL_BOOKMARKS_REQUEST";
export const REMOVE_ALL_BOOKMARKS_SUCCESS = "REMOVE_ALL_BOOKMARKS_SUCCESS";
export const REMOVE_ALL_BOOKMARKS_FAIL = "REMOVE_ALL_BOOKMARKS_FAIL";


