export const GET_HEADLINES_REQUEST = "GET_HEADLINES_REQUEST";
export const GET_HEADLINES_SUCCESS = "GET_HEADLINES_SUCCESS";
export const GET_HEADLINES_FAIL = "GET_HEADLINES_FAIL";
export const CHANGE_HEADLINE_REQUEST = "CHANGE_HEADLINE_REQUEST";
export const CHANGE_HEADLINE_SUCCESS = "CHANGE_HEADLINE_SUCCESS";
export const CHANGE_HEADLINE_FAIL = "CHANGE_HEADLINE_FAIL";
